### ISSUE TITLE
/containers Docker daemon is not running

### ISSUE THREAD

**Issue by mslusarczyk** [salihciftci/liman#4]
**Describe the bug**
1. Run from docker image with 'docker run -it -p 8090:8080 -e pass=PASS -v /var/run/docker.sock:/var/run/docker.sock salihciftci/liman'
2. Navigate to /containers
3. Observe empty page. GET request returns with 200 (empty resp)

**Expected behavior**
?

**Logs**
```
2018/06/22 08:56:25 Listening http://0.0.0.0:8080
2018/06/22 08:56:59 GET / http: named cookie not present
2018/06/22 08:57:00 GET /
2018/06/22 08:57:00 GET /login
2018/06/22 08:57:10 POST /
2018/06/22 08:57:25 GET /containers Docker daemon is not running
```

**Your environment**
Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-1047-aws x86_64)
Docker version 18.04.0-ce, build 3d479c0

**Additional context**

**Comment by salihciftci** [comment]
Hey @mslusarczyk 

That's happens when we have so much logs on containers. But it is fixed.

Can you please run these and test it again?

```
docker image rm -f salihciftci/liman:
docker run -it -p 8090:8080 -v /var/run/docker.sock:/var/run/docker.sock salihciftci/liman
```

**Comment by mslusarczyk** [comment]
@salihciftci output is changed but not in a good way:)
```
tatus: Downloaded newer image for salihciftci/liman:latest
2018/06/22 10:01:30 Listening http://0.0.0.0:8080
2018/06/22 10:01:40 mesos-d260f517-3c53-4466-90f9-a407d677949dis stopped.
2018/06/22 10:02:03 vigorous_shternis stopped.
2018/06/22 10:02:03 mesos-d260f517-3c53-4466-90f9-a407d677949d is started.
2018/06/22 10:02:03 mesos-4fcb10be-c639-45d7-974e-4254130f0ed2is stopped.
2018/06/22 10:02:03 mesos-4c61f149-420c-4d56-a287-bf3e6b5488b2 is started.
2018/06/22 10:02:03 mesos-bcbe7cea-c3a9-4885-9ef9-5433156102b5is stopped.
2018/06/22 10:02:03 mesos-a2fb2bff-a894-4bd0-9733-d0ac0c20562f is started.
2018/06/22 10:02:03 mesos-63977f6c-dad3-46cc-aaac-dd2d1797a21ais stopped.
2018/06/22 10:02:03 mesos-333cf935-0d67-49d0-92c9-4908b274aac9 is started.
2018/06/22 10:02:03 mesos-6b799d60-826f-44cd-9f4d-e2a5093a0521is stopped.
2018/06/22 10:02:03 mesos-9c2692c4-a163-404e-b238-37a20edbd014 is started.
2018/06/22 10:02:03 mesos-f5855769-136e-49fe-ae22-8f2495fd4fafis stopped.
2018/06/22 10:02:03 mesos-3e9a6842-e786-45a3-9b70-ae63b5992bbc is started.
2018/06/22 10:02:03 mesos-25cdc5e9-6a1c-4779-a969-3fc3ddbf8af3is stopped.
2018/06/22 10:02:03 mesos-aa8ee672-59b2-4b18-8755-65e565463b82 is started.
2018/06/22 10:02:03 mesos-2bce6452-0879-4956-b229-9c1ecb3ce38eis stopped.
2018/06/22 10:02:03 mesos-e891c7d6-b52c-4889-b277-e36d41d155ba is started.
2018/06/22 10:02:03 mesos-3bb49453-46ec-4f4f-825f-15c70555c221is stopped.
2018/06/22 10:02:03 mesos-12611199-8b04-4656-a0e3-21f1e0c45376 is started.
2018/06/22 10:02:03 mesos-5f598d3d-1ce3-4133-866f-4efd719a23eeis stopped.
panic: runtime error: index out of range

goroutine 50 [running]:
main.main.func1()
	/go/src/liman/main.go:384 +0x7ab
created by main.main
	/go/src/liman/main.go:370 +0x3eb
```

**Comment by salihciftci** [comment]
@mslusarczyk Whoops.

I assuming vigorous_shternis is Liman.

Is it possible to temporarily stop `mesos-12611199-8b04-4656-a0e3-21f1e0c45376` container and test it again? While it's already stopping itself. :)

**Comment by mslusarczyk** [comment]
Yes, I've removed `--name` param to `docker run`.  
With `mesos-12611199-8b04-4656-a0e3-21f1e0c45376` it still ends up in `panic`. I have 64 different containers starting and stopping there, do you think Liman will work in a setup like this?

**Comment by salihciftci** [comment]
Liman checking containers statues every second for notifications. While your containers in a panic, Liman doesn't like that. 

I tried someting ugly for temporarily. Could you please run these and test it again on more time?

```
docker image rm -f salihciftci/liman:
docker run -it -p 8090:8080 -v /var/run/docker.sock:/var/run/docker.sock salihciftci/liman
```

If it is doesn't work in a setup like that. It will soon. :)

**Comment by mslusarczyk** [comment]
It worked for some time and crashed again:
```
2018/06/22 10:57:23 GET /logs Docker daemon is not running
2018/06/22 10:57:24 GET /favicon.ico
2018/06/22 10:58:22 mesos-5e73b869-f366-43d1-8f98-e2ba21e4ac1f is started.
2018/06/22 10:58:22 mesos-cd1bbd0b-4e05-4c1e-9924-088586a796d6is stopped.
2018/06/22 10:58:22 mesos-e5eb7005-7d62-40c1-9cae-9c67ebabd00fis stopped.
2018/06/22 10:58:22 mesos-afd4e251-313b-42ed-b1cd-eca78b21eadd is started.
2018/06/22 10:58:22 mesos-759a6fbd-6f55-4c48-8fda-e24708cf9189is stopped.
2018/06/22 10:58:22 mesos-5821ff21-3999-407e-a978-9e5e3281ed28 is started.
2018/06/22 10:58:22 mesos-f66c12a5-4b4c-4ffe-8ccc-91bb7d848acais stopped.
2018/06/22 10:58:22 mesos-10bc3070-dc12-4438-9ed3-28dc2fcf2cb3 is started.
2018/06/22 10:58:22 mesos-06678e20-1b23-47d7-8536-81aa8855d5fdis stopped.
2018/06/22 10:58:22 mesos-a7d2881b-635e-404f-95fd-911484ebf7f8 is started.
2018/06/22 10:58:22 mesos-4fcb10be-c639-45d7-974e-4254130f0ed2is stopped.
2018/06/22 10:58:22 mesos-4c61f149-420c-4d56-a287-bf3e6b5488b2 is started.
2018/06/22 10:58:22 mesos-da01fff6-339c-4326-b2c6-9a0c0e1f8f92is stopped.
2018/06/22 10:58:22 mesos-9c2692c4-a163-404e-b238-37a20edbd014 is started.
2018/06/22 10:58:22 mesos-f5855769-136e-49fe-ae22-8f2495fd4fafis stopped.
2018/06/22 10:58:22 mesos-3e9a6842-e786-45a3-9b70-ae63b5992bbc is started.
2018/06/22 10:58:22 mesos-2bce6452-0879-4956-b229-9c1ecb3ce38eis stopped.
2018/06/22 10:58:22 mesos-e891c7d6-b52c-4889-b277-e36d41d155ba is started.
2018/06/22 10:58:22 mesos-3bb49453-46ec-4f4f-825f-15c70555c221is stopped.
2018/06/22 10:58:22 mesos-4f2bc216-fe78-43b1-8e17-4b47906f5f62 is started.
2018/06/22 10:58:22 mesos-78fec5d5-a27d-40fb-a320-daa8d51353dais stopped.
2018/06/22 10:58:22 mesos-7cfc889e-9627-428e-9877-0aea3aef0171 is started.
2018/06/22 10:58:22 mesos-5f598d3d-1ce3-4133-866f-4efd719a23eeis stopped.
panic: runtime error: index out of range

goroutine 35 [running]:
main.main.func1()
	/go/src/liman/main.go:384 +0x7b1
created by main.main
	/go/src/liman/main.go:370 +0x3e
```
Also, `/logs` are empty as well with the same info about docker daemon not running


Two suggestions about `/containers` view:)
1. Show only live ones by default (with a toggle) - in my setup there 200+ and only 64 live
2. Make table adaptable to long image names
<img width="1283" alt="screen shot 2018-06-22 at 12 59 12" src="https://user-images.githubusercontent.com/6906940/41773355-182f9d80-761c-11e8-9c7d-3fbf63a3fb7b.png">

**Comment by mslusarczyk** [comment]
`/containers` works fine now, thanks for your swift reaction!

**Comment by salihciftci** [comment]
Let me know if you have any issue again.
